//! C and C++ source-admission policy for generated and vendored files.

const GENERATED_MARKERS: &[&str] = &[
    "File created by MIDL compiler",
    "ALWAYS GENERATED file contains",
    "Created by: flatc compiler",
    "Generated by the protocol buffer compiler",
];

const VENDORED_PATH_SEGMENTS: &[&str] = &["third_party", "vendor", "deps", "external", "extern"];

const VENDORED_CONTENT_MARKERS: &[&str] = &[
    "JSON for Modern C++",
    "raylib v",
    "raymath v",
    "Sean Barrett",
    "Catch v",
    "Catch2 v",
    "dear imgui,",
    "GLFW 3",
    "miniaudio - Audio playback",
    "termbox2.h --",
    ".h -- Drop-in",
    ".h -- drop-in",
    ".h -- Minimal",
    ".h -- minimal",
    ".h -- Simple",
    ".h -- simple",
];

pub(crate) fn is_generated_platform_header(content: &str) -> bool {
    GENERATED_MARKERS
        .iter()
        .any(|marker| content_prefix(content, 2048).contains(marker))
}

pub(crate) fn is_vendored_source_file(path: &str, content: &str) -> bool {
    let normalized = path.replace('\\', "/");
    if VENDORED_PATH_SEGMENTS.iter().any(|segment| {
        normalized.contains(&format!("/{segment}/"))
            || normalized.ends_with(&format!("/{segment}"))
            || normalized.starts_with(&format!("{segment}/"))
    }) {
        return true;
    }
    let head = content_prefix(content, 4096);
    VENDORED_CONTENT_MARKERS
        .iter()
        .any(|marker| head.contains(marker))
}

fn content_prefix(content: &str, limit: usize) -> &str {
    let mut end = content.len().min(limit);
    while end > 0 && !content.is_char_boundary(end) {
        end -= 1;
    }
    &content[..end]
}
