// =============================================================================
// vue/auto_import_dts_tests.rs — unit tests for auto_import_dts.rs
// =============================================================================

use super::*;

#[test]
fn parse_component_map_local_vue_path() {
    let src = r#"
declare module 'vue' {
  export interface GlobalComponents {
    FooBar: typeof import('./components/foo/Bar.vue')['default']
  }
}
"#;
    let entries = parse_dts(src);
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].name, "FooBar");
    assert_eq!(entries[0].module, "./components/foo/Bar.vue");
}

#[test]
fn parse_component_map_bare_package_reexport() {
    // unplugin-vue-components emits `Name: typeof import('pkg')['Name']` when
    // the component comes from an external library, not a local file.
    let src =
        "    ExtWidget: typeof import('@scope/ui')['ExtWidget']";
    let entries = parse_dts(src);
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].name, "ExtWidget");
    assert_eq!(entries[0].module, "@scope/ui");
}

#[test]
fn parse_auto_import_global_const_composable() {
    let src = r#"
declare global {
  const useThing: typeof import('@scope/composables')['useThing']
  const ref: typeof import('vue')['ref']
}
"#;
    let entries = parse_dts(src);
    assert_eq!(entries.len(), 2);
    assert_eq!(entries[0].name, "useThing");
    assert_eq!(entries[0].module, "@scope/composables");
    assert_eq!(entries[1].name, "ref");
    assert_eq!(entries[1].module, "vue");
}

#[test]
fn skips_wrapper_and_comment_lines() {
    let src = r#"
/* eslint-disable */
// Generated by unplugin-vue-components
export {}
/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Keep: typeof import('./Keep.vue')['default']
  }
}
"#;
    let entries = parse_dts(src);
    assert_eq!(entries.len(), 1, "only the binding line is captured");
    assert_eq!(entries[0].name, "Keep");
}

#[test]
fn double_quoted_specifier() {
    let src = r#"    Widget: typeof import("./Widget.vue")["default"]"#;
    let entries = parse_dts(src);
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].module, "./Widget.vue");
}

#[test]
fn empty_input_yields_no_entries() {
    assert!(parse_dts("").is_empty());
    assert!(parse_dts("export {}\n").is_empty());
}

#[test]
fn ignores_export_default_and_other_typeof_uses() {
    // A `typeof` that is not an `import(...)` source must not produce an entry.
    let src = "  const x: typeof someValue = something";
    assert!(parse_dts(src).is_empty());
}
