// =============================================================================
// build.rs — Extract builtin/keyword names from tree-sitter highlights.scm
//
// Auto-discovers ALL tree-sitter grammar crates in the cargo registry.
// No hardcoded grammar list — any crate matching `tree-sitter-*` with a
// `queries/highlights.scm` gets processed.
//
// Extracts:
//   1. String literals in [...] @keyword blocks
//   2. String literals in [...] @*.builtin blocks
//   3. Inline "word" @keyword / "word" @*.builtin
//   4. Names from #match?/#eq? predicates on @*.builtin captures
//
// Generates `src/indexer/query_builtins.rs` with per-language builtin arrays.
// Language aliases (tsx→typescript, etc.) are NOT handled here — they live
// in the language plugin registry where they belong.
// =============================================================================

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::PathBuf;

fn main() {
    let out_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_path = PathBuf::from(&out_dir).join("src/indexer/query_builtins.rs");

    let home = std::env::var("CARGO_HOME")
        .or_else(|_| std::env::var("HOME").map(|h| format!("{h}/.cargo")))
        .or_else(|_| std::env::var("USERPROFILE").map(|h| format!("{h}/.cargo")))
        .unwrap_or_else(|_| String::from(".cargo"));
    let registry_src = PathBuf::from(&home).join("registry/src");

    let mut all_builtins: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();

    // Scan all index directories in the cargo registry.
    if let Ok(index_dirs) = fs::read_dir(&registry_src) {
        for index_entry in index_dirs.flatten() {
            let index_path = index_entry.path();
            if !index_path.is_dir() {
                continue;
            }
            if let Ok(crate_dirs) = fs::read_dir(&index_path) {
                for crate_entry in crate_dirs.flatten() {
                    let crate_name = crate_entry.file_name().to_string_lossy().to_string();
                    let crate_path = crate_entry.path();

                    // Auto-discover: any directory matching tree-sitter-*
                    let Some(lang_id) = extract_lang_id(&crate_name) else {
                        continue;
                    };

                    // Only process if it has highlights.scm — that's where
                    // builtins and keywords are tagged. locals.scm defines
                    // scope/definition/reference patterns (no builtin names).
                    let highlights = crate_path.join("queries/highlights.scm");
                    if !highlights.exists() {
                        continue;
                    }

                    let names = all_builtins.entry(lang_id).or_default();

                    if let Ok(content) = fs::read_to_string(&highlights) {
                        extract_builtins_from_scm(&content, names);
                    }
                }
            }
        }
    }

    // Generate the Rust source file.
    let mut output = String::new();
    output.push_str(
        "// AUTO-GENERATED by build.rs — do not edit manually.\n\
         // Extracted from tree-sitter grammar query files (highlights.scm + locals.scm).\n\
         //\n\
         // Language IDs are derived from crate names: tree-sitter-foo-1.2.3 → \"foo\".\n\
         // Aliases (tsx→typescript, etc.) are handled by the language plugin registry,\n\
         // NOT here — build.rs only knows about crate names.\n\n\
         /// Return query-extracted builtins for a language.\n\
         /// Returns an empty slice for languages without query files.\n\
         pub fn query_builtins_for_language(lang: &str) -> &'static [&'static str] {\n\
         \x20   match lang {\n",
    );

    for (lang, names) in &all_builtins {
        let filtered: Vec<&String> = names
            .iter()
            .filter(|n| n.len() > 1 && n.starts_with(|c: char| c.is_alphanumeric() || c == '_'))
            .collect();
        if filtered.is_empty() {
            continue;
        }
        output.push_str(&format!("        \"{}\" => &[\n", lang));
        for name in &filtered {
            output.push_str(&format!(
                "            \"{}\",\n",
                name.replace('"', "\\\"")
            ));
        }
        output.push_str("        ],\n");
    }

    output.push_str("        _ => &[],\n    }\n}\n");

    fs::write(&out_path, &output).expect("Failed to write query_builtins.rs");

    // Rerun only when build.rs itself changes. Grammar query files in the
    // cargo registry are stable per-version — they only change when crate
    // versions are bumped in Cargo.toml.
    println!("cargo:rerun-if-changed=build.rs");
}

/// Derive a BearWisdom language ID from a tree-sitter crate directory name.
///
/// Examples:
///   "tree-sitter-rust-0.24.0"     → Some("rust")
///   "tree-sitter-c-sharp-0.23.1"  → Some("c-sharp")
///   "tree-sitter-c-0.24.1"        → Some("c")
///   "tree-sitter-go-0.25.0"       → Some("go")
///   "tree-sitter-kotlin-ng-0.1.0" → Some("kotlin-ng")
///   "not-a-grammar"               → None
fn extract_lang_id(crate_dir_name: &str) -> Option<String> {
    let rest = crate_dir_name.strip_prefix("tree-sitter-")?;

    // Strip the version suffix: find the last `-DIGIT` boundary.
    // Walk from the end to find where the version starts.
    // Version is always `-N.N.N` at the end.
    let mut version_start = None;
    let bytes = rest.as_bytes();
    for i in (1..bytes.len()).rev() {
        if bytes[i - 1] == b'-' && bytes[i].is_ascii_digit() {
            // Check this looks like a version: digits, dots, possibly more digits.
            let tail = &rest[i..];
            if tail
                .chars()
                .all(|c| c.is_ascii_digit() || c == '.' || c == '-')
            {
                version_start = Some(i - 1);
                break;
            }
        }
    }

    let lang_part = match version_start {
        Some(pos) => &rest[..pos],
        None => rest,
    };

    if lang_part.is_empty() {
        return None;
    }

    // Normalize crate naming conventions to BearWisdom language IDs.
    // This is NOT an alias system — it's purely fixing crate naming mismatches.
    let normalized = match lang_part {
        "c-sharp" => "csharp",
        "vb-dotnet" => "vbnet",
        "kotlin-ng" => "kotlin",
        "sequel" => "sql",
        "scss-local" => "scss",
        "dockerfile-0-25" => "dockerfile",
        "md" => "markdown",
        other => other,
    };

    Some(normalized.to_string())
}

// ---------------------------------------------------------------------------
// SCM extraction
// ---------------------------------------------------------------------------

fn extract_builtins_from_scm(content: &str, names: &mut BTreeSet<String>) {
    extract_match_predicates(content, names);
    extract_eq_predicates(content, names);
    extract_keyword_strings(content, names);
    extract_builtin_strings(content, names);
}

fn extract_match_predicates(content: &str, names: &mut BTreeSet<String>) {
    let re = regex::Regex::new(
        r#"#match\?\s+@\w+(?:\.\w+)?\s+"[^^]*\^?\(([^)]+)\)\$?""#,
    )
    .unwrap();
    for cap in re.captures_iter(content) {
        if let Some(alt) = cap.get(1) {
            for name in alt.as_str().split('|') {
                let name = name.trim();
                if !name.is_empty() {
                    names.insert(name.to_string());
                }
            }
        }
    }
}

fn extract_eq_predicates(content: &str, names: &mut BTreeSet<String>) {
    let re = regex::Regex::new(r#"#eq\?\s+@\w+(?:\.\w+)?\s+"([^"]+)""#).unwrap();
    for cap in re.captures_iter(content) {
        if let Some(name) = cap.get(1) {
            names.insert(name.as_str().to_string());
        }
    }
}

fn extract_keyword_strings(content: &str, names: &mut BTreeSet<String>) {
    // Inline: "word" @keyword
    let re = regex::Regex::new(
        r#""([a-zA-Z_][a-zA-Z0-9_!?]*(?:::)?[a-zA-Z0-9_!?]*)"\s+@keyword"#,
    )
    .unwrap();
    for cap in re.captures_iter(content) {
        if let Some(name) = cap.get(1) {
            names.insert(name.as_str().to_string());
        }
    }
    // Bracket blocks: [...] @keyword
    extract_bracket_block_names(content, "@keyword", names);
}

fn extract_builtin_strings(content: &str, names: &mut BTreeSet<String>) {
    // Inline: "word" @*.builtin
    let re = regex::Regex::new(r#""([a-zA-Z_][a-zA-Z0-9_!?]*)"\s+@\w+\.builtin"#).unwrap();
    for cap in re.captures_iter(content) {
        if let Some(name) = cap.get(1) {
            names.insert(name.as_str().to_string());
        }
    }
    // Bracket blocks: [...] @type.builtin, [...] @constant.builtin, etc.
    for tag in [
        "@type.builtin",
        "@constant.builtin",
        "@function.builtin",
        "@variable.builtin",
    ] {
        extract_bracket_block_names(content, tag, names);
    }
}

/// Extract quoted names from `[ "w1" "w2" ... ] @tag` blocks.
fn extract_bracket_block_names(content: &str, tag: &str, names: &mut BTreeSet<String>) {
    let re_quoted = regex::Regex::new(r#""([a-zA-Z_][a-zA-Z0-9_!?]*)""#).unwrap();
    let needle = format!("] {}", tag);
    let mut pos = 0;
    while let Some(found) = content[pos..].find(&needle) {
        let abs = pos + found;
        if let Some(open) = content[..abs].rfind('[') {
            for cap in re_quoted.captures_iter(&content[open..abs]) {
                if let Some(name) = cap.get(1) {
                    names.insert(name.as_str().to_string());
                }
            }
        }
        pos = abs + needle.len();
    }
}
