// =============================================================================
// ecosystem/clay_ui_synthetics.rs — Clay UI single-header library stubs
//
// Clay is a single-header C UI library whose internal array types are
// generated by the macro:
//
//     CLAY__ARRAY_DEFINE(TYPE, NAME)
//
// which expands to NAME ## Array, NAME ## Array_Add, NAME ## Array_Get,
// NAME ## Array_Set, NAME ## Array_Allocate_Arena, etc. Tree-sitter parses
// the raw macro invocations but cannot expand them, so the fully-qualified
// function names never appear as symbols in the index, leaving every call
// site as an unresolved ref.
//
// Clay also defines several CLAY_* enum constant families (alignment,
// attach-point, text-wrap, etc.) whose definitions live inside
// `#if defined(CLAY_IMPLEMENTATION)` blocks that are conditionally compiled
// but unconditionally referenced.
//
// This module synthesises:
//   * Every CLAY__ARRAY_DEFINE instantiation used by cpp-clay (the
//     concrete type/name pairs observed in the unresolved-refs table).
//   * The CLAY_* enum constants that appear as unresolved refs.
//   * Public types like Clay_RectangleElementConfig that the extractor
//     misses due to typedef-inside-macro patterns.
//
// Activation: a `clay.h` file is present in the project root (the
// canonical distribution shape for this single-header library). The
// locate_roots implementation returns an empty vec when clay.h is absent,
// which prevents the ecosystem from firing on unrelated C projects.
// =============================================================================

use std::path::Path;

use super::{Ecosystem, EcosystemActivation, EcosystemId, EcosystemKind, LocateContext};
use crate::ecosystem::externals::{ExternalDepRoot, ExternalSourceLocator};
use crate::types::{ExtractedSymbol, ParsedFile, SymbolKind, Visibility};
use crate::walker::WalkedFile;

pub const ID: EcosystemId = EcosystemId::new("clay-ui-synthetics");
const TAG: &str = "clay-ui-synthetics";
const LANGUAGES: &[&str] = &["c", "cpp"];

// ---------------------------------------------------------------------------
// Clay__ARRAY_DEFINE instantiations that appear in cpp-clay's unresolved refs
//
// Each tuple is (type_name, array_name) matching the CLAY__ARRAY_DEFINE(T, N)
// invocation. This expands to:
//   N                  — struct typedef (TypeRef)
//   N_Add              — function
//   N_Allocate_Arena   — function
//   N_Get              — function
//   N_GetCheckCapacity — function (not all types)
//   N_GetValue         — function (int32_t only)
//   N_RemoveSwapback   — function (some types)
//   N_Set              — function
//   N_Set_DontTouchLength — function (some types)
//   NSlice             — struct typedef (some types)
//   NSlice_Get         — function (slice types)
// ---------------------------------------------------------------------------

/// (array_struct_name, has_get_value, has_remove_swapback, has_set_dont_touch,
///  has_get_check_capacity, has_slice)
struct ArrayDef {
    name: &'static str,
    has_get_value: bool,
    has_remove_swapback: bool,
    has_set_dont_touch: bool,
    has_get_check_capacity: bool,
    has_slice: bool,
    has_set: bool,
}

const ARRAY_DEFS: &[ArrayDef] = &[
    ArrayDef {
        name: "Clay__int32_tArray",
        has_get_value: true,
        has_remove_swapback: true,
        has_set_dont_touch: true,
        has_get_check_capacity: true,
        has_slice: false,
        has_set: true,
    },
    ArrayDef {
        name: "Clay_LayoutElementArray",
        has_get_value: false,
        has_remove_swapback: false,
        has_set_dont_touch: true,
        has_get_check_capacity: true,
        has_slice: false,
        has_set: false,
    },
    ArrayDef {
        name: "Clay_ElementIdArray",
        has_get_value: false,
        has_remove_swapback: false,
        has_set_dont_touch: false,
        has_get_check_capacity: false,
        has_slice: false,
        has_set: false,
    },
    ArrayDef {
        name: "Clay_RenderCommandArray",
        has_get_value: false,
        has_remove_swapback: false,
        has_set_dont_touch: false,
        has_get_check_capacity: false,
        has_slice: false,
        has_set: false,
    },
    ArrayDef {
        name: "Clay__ScrollContainerDataInternalArray",
        has_get_value: false,
        has_remove_swapback: true,
        has_set_dont_touch: false,
        has_get_check_capacity: false,
        has_slice: false,
        has_set: false,
    },
    ArrayDef {
        name: "Clay__LayoutElementTreeRootArray",
        has_get_value: false,
        has_remove_swapback: false,
        has_set_dont_touch: false,
        has_get_check_capacity: false,
        has_slice: false,
        has_set: true,
    },
    ArrayDef {
        name: "Clay__LayoutElementTreeNodeArray",
        has_get_value: false,
        has_remove_swapback: false,
        has_set_dont_touch: false,
        has_get_check_capacity: false,
        has_slice: false,
        has_set: false,
    },
    ArrayDef {
        name: "Clay__LayoutElementHashMapItemArray",
        has_get_value: false,
        has_remove_swapback: false,
        has_set_dont_touch: false,
        has_get_check_capacity: false,
        has_slice: false,
        has_set: false,
    },
    ArrayDef {
        name: "Clay__MeasureTextCacheItemArray",
        has_get_value: false,
        has_remove_swapback: false,
        has_set_dont_touch: false,
        has_get_check_capacity: false,
        has_slice: false,
        has_set: true,
    },
    ArrayDef {
        name: "Clay__MeasuredWordArray",
        has_get_value: false,
        has_remove_swapback: false,
        has_set_dont_touch: false,
        has_get_check_capacity: false,
        has_slice: false,
        has_set: true,
    },
    ArrayDef {
        name: "Clay__StringArray",
        has_get_value: false,
        has_remove_swapback: false,
        has_set_dont_touch: true,
        has_get_check_capacity: true,
        has_slice: false,
        has_set: false,
    },
    ArrayDef {
        name: "Clay__WrappedTextLineArray",
        has_get_value: false,
        has_remove_swapback: false,
        has_set_dont_touch: false,
        has_get_check_capacity: false,
        has_slice: true,
        has_set: false,
    },
    ArrayDef {
        name: "Clay__TransitionDataInternalArray",
        has_get_value: false,
        has_remove_swapback: true,
        has_set_dont_touch: false,
        has_get_check_capacity: false,
        has_slice: false,
        has_set: false,
    },
    ArrayDef {
        name: "Clay__DebugElementDataArray",
        has_get_value: false,
        has_remove_swapback: false,
        has_set_dont_touch: false,
        has_get_check_capacity: false,
        has_slice: false,
        has_set: false,
    },
    ArrayDef {
        name: "Clay__boolArray",
        has_get_value: false,
        has_remove_swapback: false,
        has_set_dont_touch: false,
        has_get_check_capacity: false,
        has_slice: false,
        has_set: false,
    },
    ArrayDef {
        name: "Clay__charArray",
        has_get_value: false,
        has_remove_swapback: false,
        has_set_dont_touch: false,
        has_get_check_capacity: false,
        has_slice: false,
        has_set: false,
    },
];

// ---------------------------------------------------------------------------
// CLAY_* enum constants (alignment, attach-point, text-wrap, sizing, etc.)
// ---------------------------------------------------------------------------

const CLAY_ENUM_CONSTANTS: &[&str] = &[
    // Clay_ChildAlignment (X axis)
    "CLAY_ALIGN_X_LEFT",
    "CLAY_ALIGN_X_CENTER",
    "CLAY_ALIGN_X_RIGHT",
    // Clay_ChildAlignment (Y axis)
    "CLAY_ALIGN_Y_TOP",
    "CLAY_ALIGN_Y_CENTER",
    "CLAY_ALIGN_Y_BOTTOM",
    // Clay_FloatingAttachPointType
    "CLAY_ATTACH_POINT_LEFT_TOP",
    "CLAY_ATTACH_POINT_LEFT_CENTER",
    "CLAY_ATTACH_POINT_LEFT_BOTTOM",
    "CLAY_ATTACH_POINT_CENTER_TOP",
    "CLAY_ATTACH_POINT_CENTER_CENTER",
    "CLAY_ATTACH_POINT_CENTER_BOTTOM",
    "CLAY_ATTACH_POINT_RIGHT_TOP",
    "CLAY_ATTACH_POINT_RIGHT_CENTER",
    "CLAY_ATTACH_POINT_RIGHT_BOTTOM",
    // Clay_FloatingAttachToElement
    "CLAY_ATTACH_TO_NONE",
    "CLAY_ATTACH_TO_PARENT",
    "CLAY_ATTACH_TO_ELEMENT_WITH_ID",
    "CLAY_ATTACH_TO_ROOT",
    // Clay_ErrorType
    "CLAY_ERROR_TYPE_PERCENTAGE_OVER_1",
    "CLAY_ERROR_TYPE_UNBALANCED_OPEN_CLOSE",
    // Clay_LayoutDirection
    "CLAY_LEFT_TO_RIGHT",
    "CLAY_TOP_TO_BOTTOM",
    // Clay_PointerCaptureMode
    "CLAY_POINTER_CAPTURE_MODE_CAPTURE",
    "CLAY_POINTER_CAPTURE_MODE_PASSTHROUGH",
    // Clay_RenderCommandType (internal/debug)
    "CLAY_RENDER_COMMAND_TYPE_OVERLAY_COLOR_START",
    "CLAY_RENDER_COMMAND_TYPE_OVERLAY_COLOR_END",
    // Clay_TextAlignment
    "CLAY_TEXT_ALIGN_LEFT",
    "CLAY_TEXT_ALIGN_CENTER",
    "CLAY_TEXT_ALIGN_RIGHT",
    // Clay_TextWrapping
    "CLAY_TEXT_WRAP_WORDS",
    "CLAY_TEXT_WRAP_NEWLINES",
    "CLAY_TEXT_WRAP_NONE",
    // Clay__SizingType (internal)
    "CLAY__SIZING_TYPE_FIT",
    "CLAY__SIZING_TYPE_FIXED",
    "CLAY__SIZING_TYPE_GROW",
    "CLAY__SIZING_TYPE_PERCENT",
];

// ---------------------------------------------------------------------------
// Public types that the extractor misses (macro-wrapped typedefs / structs)
// ---------------------------------------------------------------------------

const CLAY_TYPES: &[(&str, SymbolKind)] = &[
    ("Clay_RectangleElementConfig", SymbolKind::Struct),
];

// ---------------------------------------------------------------------------
// Internal debug/render functions (appear as call targets in clay.h itself)
// ---------------------------------------------------------------------------

const CLAY_FUNCTIONS: &[&str] = &[
    "Clay__RenderDebugLayoutElementsList",
    "Clay__RenderDebugLayoutSizing",
    "Clay__RenderDebugView",
    "Clay__RenderDebugViewColor",
    "Clay__RenderDebugViewCornerRadius",
    "Clay__RenderElementConfigTypeLabel",
    "Clay__DebugViewRenderElementConfigHeader",
    // Project-specific layout function from playdate example (project-local
    // but defined in a separate compilation unit, thus unresolved from callers)
    "ClayVideoDemoPlaydate_CreateLayout",
];

// ---------------------------------------------------------------------------
// Symbol builder helpers
// ---------------------------------------------------------------------------

fn fn_sym(name: &str) -> ExtractedSymbol {
    ExtractedSymbol {
        name: name.to_string(),
        qualified_name: name.to_string(),
        kind: SymbolKind::Function,
        visibility: Some(Visibility::Public),
        start_line: 0,
        end_line: 0,
        start_col: 0,
        end_col: 0,
        signature: Some(format!("/* clay macro-generated */ void {name}()")),
        doc_comment: None,
        scope_path: None,
        parent_index: None,
    }
}

fn enum_sym(name: &str) -> ExtractedSymbol {
    ExtractedSymbol {
        name: name.to_string(),
        qualified_name: name.to_string(),
        kind: SymbolKind::EnumMember,
        visibility: Some(Visibility::Public),
        start_line: 0,
        end_line: 0,
        start_col: 0,
        end_col: 0,
        signature: Some(format!("/* clay enum constant */ {name}")),
        doc_comment: None,
        scope_path: None,
        parent_index: None,
    }
}

fn struct_sym(name: &str, kind: SymbolKind) -> ExtractedSymbol {
    ExtractedSymbol {
        name: name.to_string(),
        qualified_name: name.to_string(),
        kind,
        visibility: Some(Visibility::Public),
        start_line: 0,
        end_line: 0,
        start_col: 0,
        end_col: 0,
        signature: Some(format!("/* clay type */ typedef struct {name} {name}")),
        doc_comment: None,
        scope_path: None,
        parent_index: None,
    }
}

fn synthesize_file() -> ParsedFile {
    let mut symbols: Vec<ExtractedSymbol> = Vec::new();

    // 1. CLAY__ARRAY_DEFINE expansions
    for def in ARRAY_DEFS {
        let n = def.name;
        // The array struct itself
        symbols.push(struct_sym(n, SymbolKind::Struct));
        // Always present: _Add, _Get, _Allocate_Arena
        symbols.push(fn_sym(&format!("{n}_Add")));
        symbols.push(fn_sym(&format!("{n}_Get")));
        symbols.push(fn_sym(&format!("{n}_Allocate_Arena")));
        if def.has_get_value       { symbols.push(fn_sym(&format!("{n}_GetValue"))); }
        if def.has_remove_swapback { symbols.push(fn_sym(&format!("{n}_RemoveSwapback"))); }
        if def.has_set_dont_touch  { symbols.push(fn_sym(&format!("{n}_Set_DontTouchLength"))); }
        if def.has_get_check_capacity { symbols.push(fn_sym(&format!("{n}_GetCheckCapacity"))); }
        if def.has_set             { symbols.push(fn_sym(&format!("{n}_Set"))); }
        if def.has_slice {
            let slice = format!("{n}Slice");
            symbols.push(struct_sym(&slice, SymbolKind::Struct));
            symbols.push(fn_sym(&format!("{slice}_Get")));
        }
    }

    // 2. CLAY_* enum constants
    for &c in CLAY_ENUM_CONSTANTS {
        symbols.push(enum_sym(c));
    }

    // 3. Public types
    for &(name, kind) in CLAY_TYPES {
        symbols.push(struct_sym(name, kind));
    }

    // 4. Internal functions
    for &f in CLAY_FUNCTIONS {
        symbols.push(fn_sym(f));
    }

    let n = symbols.len();
    ParsedFile {
        path: "ext:clay-ui-synthetics:clay_generated.h".to_string(),
        language: "c".to_string(),
        content_hash: format!("clay-ui-synthetics-{n}"),
        size: 0,
        line_count: 0,
        mtime: None,
        package_id: None,
        symbols,
        refs: Vec::new(),
        routes: Vec::new(),
        db_sets: Vec::new(),
        symbol_origin_languages: vec![None; n],
        ref_origin_languages: Vec::new(),
        symbol_from_snippet: vec![false; n],
        content: None,
        has_errors: false,
        flow: crate::types::FlowMeta::default(),
        connection_points: Vec::new(),
        demand_contributions: Vec::new(),
    }
}

fn synthetic_dep_root() -> ExternalDepRoot {
    ExternalDepRoot {
        module_path: "clay-ui-synthetics".to_string(),
        version: String::new(),
        root: std::path::PathBuf::from("ext:clay-ui-synthetics"),
        ecosystem: TAG,
        package_id: None,
        requested_imports: Vec::new(),
    }
}

/// Probe the project root for `clay.h`.
///
/// cpp-clay distributes the library as a single header at the project root.
/// We also accept it one level deep (e.g., `vendor/clay.h`, `include/clay.h`)
/// so forks that vendor it in a subdirectory are covered too.
fn project_has_clay_header(project_root: &Path) -> bool {
    if project_root.join("clay.h").is_file() {
        return true;
    }
    // One level of subdirectory search to cover vendor/include patterns.
    let Ok(entries) = std::fs::read_dir(project_root) else { return false };
    for entry in entries.flatten() {
        let Ok(ft) = entry.file_type() else { continue };
        if ft.is_dir() && entry.path().join("clay.h").is_file() {
            return true;
        }
    }
    false
}

// ---------------------------------------------------------------------------
// Ecosystem impl
// ---------------------------------------------------------------------------

pub struct ClayUiSyntheticsEcosystem;

impl Ecosystem for ClayUiSyntheticsEcosystem {
    fn id(&self) -> EcosystemId { ID }
    fn kind(&self) -> EcosystemKind { EcosystemKind::Stdlib }
    fn languages(&self) -> &'static [&'static str] { LANGUAGES }

    fn activation(&self) -> EcosystemActivation {
        // Gate on C being present; the clay.h presence check happens in
        // locate_roots so we don't need a file-scan activation variant.
        EcosystemActivation::Any(&[
            EcosystemActivation::LanguagePresent("c"),
            EcosystemActivation::LanguagePresent("cpp"),
        ])
    }

    fn locate_roots(&self, ctx: &LocateContext<'_>) -> Vec<ExternalDepRoot> {
        if !project_has_clay_header(ctx.project_root) {
            return Vec::new();
        }
        vec![synthetic_dep_root()]
    }

    fn walk_root(&self, _dep: &ExternalDepRoot) -> Vec<WalkedFile> {
        Vec::new()
    }

    fn uses_demand_driven_parse(&self) -> bool { true }

    fn parse_metadata_only(&self, _dep: &ExternalDepRoot) -> Option<Vec<ParsedFile>> {
        Some(vec![synthesize_file()])
    }
}

impl ExternalSourceLocator for ClayUiSyntheticsEcosystem {
    fn ecosystem(&self) -> &'static str { TAG }

    fn locate_roots(&self, project_root: &Path) -> Vec<ExternalDepRoot> {
        if !project_has_clay_header(project_root) {
            return Vec::new();
        }
        vec![synthetic_dep_root()]
    }

    fn parse_metadata_only(&self, _project_root: &Path) -> Option<Vec<ParsedFile>> {
        Some(vec![synthesize_file()])
    }
}

#[cfg(test)]
#[path = "clay_ui_synthetics_tests.rs"]
mod tests;
