// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `ada` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "abort",
    "abs",
    "abstract",
    "accept",
    "access",
    "all",
    "and",
    "array",
    "at",
    "begin",
    "body",
    "constant",
    "declare",
    "delay",
    "delta",
    "digits",
    "do",
    "end",
    "entry",
    "exit",
    "function",
    "generic",
    "in",
    "interface",
    "is",
    "limited",
    "mod",
    "new",
    "not",
    "null",
    "of",
    "or",
    "others",
    "out",
    "overriding",
    "package",
    "pragma",
    "private",
    "procedure",
    "protected",
    "range",
    "record",
    "return",
    "separate",
    "subtype",
    "synchronized",
    "tagged",
    "task",
    "terminate",
    "type",
    "until",
    "when",
    "with",
    "xor",
];

pub const LOCALS_SCM: Option<&str> = Some(
    ";;  Better highlighting by referencing to the definition, for variable\n\
;;  references. However, this is not yet supported by neovim\n\
;;  See https://tree-sitter.github.io/tree-sitter/syntax-highlighting#local-variables\n\
\n\
(compilation) @scope\n\
(package_declaration) @scope\n\
(package_body) @scope\n\
(subprogram_declaration) @scope\n\
(subprogram_body) @scope\n\
(block_statement) @scope\n\
\n\
(with_clause (_) @definition.import)\n\
(procedure_specification name: (_) @definition.function)\n\
(function_specification name: (_) @definition.function)\n\
(package_declaration name: (_) @definition.var)\n\
(package_body name: (_) @definition.var)\n\
(generic_instantiation . name: (_) @definition.var)\n\
(component_declaration . (identifier) @definition.var)\n\
(exception_declaration . (identifier) @definition.var)\n\
(formal_object_declaration . (identifier) @definition.var)\n\
(object_declaration . (identifier) @definition.var)\n\
(parameter_specification . (identifier) @definition.var)\n\
(full_type_declaration . (identifier) @definition.type)\n\
(private_type_declaration . (identifier) @definition.type)\n\
(private_extension_declaration . (identifier) @definition.type)\n\
(incomplete_type_declaration . (identifier) @definition.type)\n\
(protected_type_declaration . (identifier) @definition.type)\n\
(formal_complete_type_declaration . (identifier) @definition.type)\n\
(formal_incomplete_type_declaration . (identifier) @definition.type)\n\
(task_type_declaration . (identifier) @definition.type)\n\
(subtype_declaration . (identifier) @definition.type)\n\
\n\
(identifier) @reference\n\
",
);
