// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `bicep` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "as",
    "assert",
    "existing",
    "for",
    "from",
    "func",
    "if",
    "import",
    "in",
    "metadata",
    "module",
    "output",
    "param",
    "provider",
    "resource",
    "sys",
    "targetScope",
    "test",
    "type",
    "using",
    "var",
    "with",
];

pub const LOCALS_SCM: Option<&str> = Some(
    "; Scopes\n\
[\n\
  (infrastructure)\n\
  (call_expression)\n\
  (lambda_expression)\n\
  (subscript_expression)\n\
  (if_statement)\n\
  (for_statement)\n\
  (array)\n\
  (object)\n\
  (interpolation)\n\
] @local.scope\n\
\n\
; References\n\
(property_identifier) @local.reference\n\
\n\
(call_expression\n\
  (identifier) @local.reference)\n\
\n\
(object_property\n\
  (_)\n\
  \":\"\n\
  (identifier) @local.reference)\n\
\n\
(resource_expression\n\
  (identifier) @local.reference)\n\
\n\
; Definitions\n\
(type) @local.definition.associated\n\
\n\
(object_property\n\
  (identifier) @local.definition.field\n\
  (_))\n\
\n\
(object_property\n\
  (compatible_identifier) @local.definition.field\n\
  (_))\n\
\n\
(user_defined_function\n\
  name: (identifier) @local.definition.function)\n\
\n\
(module_declaration\n\
  (identifier) @local.definition.namespace)\n\
\n\
(parameter_declaration\n\
  (identifier) @local.definition.parameter\n\
  (_))\n\
\n\
(parameter\n\
  .\n\
  (identifier) @local.definition.parameter)\n\
\n\
(type_declaration\n\
  (identifier) @local.definition.type\n\
  (_))\n\
\n\
(variable_declaration\n\
  (identifier) @local.definition.var\n\
  (_))\n\
\n\
(metadata_declaration\n\
  (identifier) @local.definition.var\n\
  (_))\n\
\n\
(output_declaration\n\
  (identifier) @local.definition.var\n\
  (_))\n\
\n\
(for_statement\n\
  \"for\"\n\
  (for_loop_parameters\n\
    (loop_variable) @local.definition.var\n\
    (loop_enumerator) @local.definition.var))\n\
",
);
