// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `cmake` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "OUTPUT_VARIABLE",
    "TRANSFORM",
];

pub const LOCALS_SCM: Option<&str> = None;
