// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `cpp` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "catch",
    "class",
    "co_await",
    "co_return",
    "co_yield",
    "concept",
    "consteval",
    "constexpr",
    "constinit",
    "delete",
    "explicit",
    "final",
    "friend",
    "mutable",
    "namespace",
    "new",
    "noexcept",
    "override",
    "private",
    "protected",
    "public",
    "requires",
    "template",
    "throw",
    "try",
    "typename",
    "using",
    "virtual",
];

pub const LOCALS_SCM: Option<&str> = None;
