// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `dart` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "Function",
    "Future",
    "Iterable",
    "List",
    "Map",
    "Never",
    "Object",
    "Runes",
    "Set",
    "Stream",
    "String",
    "Symbol",
    "abstract",
    "as",
    "assert",
    "async",
    "augment",
    "await",
    "base",
    "bool",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "covariant",
    "default",
    "deferred",
    "do",
    "double",
    "dynamic",
    "else",
    "enum",
    "export",
    "extends",
    "extension",
    "external",
    "factory",
    "final",
    "finally",
    "for",
    "get",
    "hide",
    "if",
    "implements",
    "import",
    "in",
    "inline",
    "int",
    "interface",
    "is",
    "late",
    "library",
    "mixin",
    "native",
    "new",
    "num",
    "on",
    "operator",
    "part",
    "required",
    "return",
    "sealed",
    "set",
    "show",
    "static",
    "super",
    "switch",
    "this",
    "throw",
    "try",
    "type",
    "typedef",
    "var",
    "when",
    "while",
    "with",
    "yield",
];

pub const LOCALS_SCM: Option<&str> = Some("; locals.scm - Dart scope and variable resolution queries\n\
\n\
; ============================================================================\n\
; Scopes\n\
; ============================================================================\n\
\n\
[\n\
  (class_declaration)\n\
  (mixin_declaration)\n\
  (extension_declaration)\n\
  (extension_type_declaration)\n\
  (enum_declaration)\n\
  (function_body)\n\
  (function_expression)\n\
  (block)\n\
  (for_statement)\n\
  (try_statement)\n\
  (catch_clause)\n\
  (finally_clause)\n\
  (switch_statement_case)\n\
] @local.scope\n\
\n\
; ============================================================================\n\
; Definitions\n\
; ============================================================================\n\
\n\
; Variables\n\
(initialized_variable_definition\n\
  name: (identifier) @local.definition)\n\
\n\
(initialized_identifier\n\
  (identifier) @local.definition)\n\
\n\
(static_final_declaration\n\
  (identifier) @local.definition)\n\
\n\
; Parameters\n\
(formal_parameter\n\
  (identifier) @local.definition)\n\
\n\
(constructor_param\n\
  (identifier) @local.definition)\n\
\n\
(super_formal_parameter\n\
  (identifier) @local.definition)\n\
\n\
; Catch variables\n\
(catch_clause\n\
  exception: (identifier) @local.definition)\n\
\n\
(catch_clause\n\
  stack_trace: (identifier) @local.definition)\n\
\n\
; Functions\n\
(function_signature\n\
  name: (identifier) @local.definition)\n\
\n\
(getter_signature\n\
  name: (identifier) @local.definition)\n\
\n\
(setter_signature\n\
  name: (identifier) @local.definition)\n\
\n\
; Types\n\
(class_declaration\n\
  name: (identifier) @local.definition)\n\
\n\
(mixin_declaration\n\
  (identifier) @local.definition)\n\
\n\
(enum_declaration\n\
  name: (identifier) @local.definition)\n\
\n\
(extension_declaration\n\
  name: (identifier) @local.definition)\n\
\n\
(type_alias\n\
  (type_identifier) @local.definition)\n\
\n\
(type_parameter\n\
  (type_identifier) @local.definition)\n\
\n\
; Import aliases\n\
(import_specification\n\
  alias: (identifier) @local.definition)\n\
\n\
; Pattern bindings (Dart 3.0)\n\
(variable_pattern\n\
  name: (identifier) @local.definition)\n\
\n\
; ============================================================================\n\
; References\n\
; ============================================================================\n\
\n\
(identifier) @local.reference\n\
(type_identifier) @local.reference\n\
");
