// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `dockerfile` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "ADD",
    "ARG",
    "AS",
    "CMD",
    "COPY",
    "CROSS_BUILD",
    "ENTRYPOINT",
    "ENV",
    "EXPOSE",
    "FROM",
    "HEALTHCHECK",
    "LABEL",
    "MAINTAINER",
    "ONBUILD",
    "RUN",
    "SHELL",
    "STOPSIGNAL",
    "USER",
    "VOLUME",
    "WORKDIR",
];

pub const LOCALS_SCM: Option<&str> = None;
