// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `fsharp` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "Literal",
    "abstract",
    "and",
    "as",
    "assert",
    "begin",
    "class",
    "default",
    "delegate",
    "do",
    "do!",
    "done",
    "downcast",
    "downto",
    "elif",
    "else",
    "end",
    "enum",
    "exception",
    "finally",
    "for",
    "fun",
    "function",
    "get",
    "global",
    "if",
    "in",
    "inherit",
    "inline",
    "interface",
    "lazy",
    "let",
    "let!",
    "match",
    "match!",
    "member",
    "module",
    "mutable",
    "namespace",
    "new",
    "not",
    "null",
    "of",
    "open",
    "or",
    "override",
    "rec",
    "return",
    "return!",
    "set",
    "static",
    "struct",
    "then",
    "to",
    "try",
    "type",
    "upcast",
    "use",
    "use!",
    "val",
    "when",
    "while",
    "with",
    "yield",
    "yield!",
];

pub const LOCALS_SCM: Option<&str> = Some("(identifier) @local.reference\n\
\n\
[\n\
  (namespace)\n\
  (named_module)\n\
  (function_or_value_defn)\n\
] @local.scope\n\
\n\
(value_declaration_left\n\
  .\n\
  [\n\
   (_ (identifier) @local.definition.var)\n\
   (_ (_ (identifier) @local.definition.var))\n\
   (_ (_ (_ (identifier) @local.definition.var)))\n\
   (_ (_ (_ (_ (identifier) @local.definition.var))))\n\
   (_ (_ (_ (_ (_ (identifier) @local.definition.var)))))\n\
   (_ (_ (_ (_ (_ (_ (identifier) @local.definition.var))))))\n\
  ])\n\
\n\
(function_declaration_left\n\
  .\n\
  ((_) @local.definition.function\n\
   (#set! \"definition.function.scope\" \"parent\"))\n\
  ((argument_patterns\n\
    [\n\
     (_ (identifier) @local.definition.parameter)\n\
     (_ (_ (identifier) @local.definition.parameter))\n\
     (_ (_ (_ (identifier) @local.definition.parameter)))\n\
     (_ (_ (_ (_ (identifier) @local.definition.parameter))))\n\
     (_ (_ (_ (_ (_ (identifier) @local.definition.parameter)))))\n\
     (_ (_ (_ (_ (_ (_ (identifier) @local.definition.parameter))))))\n\
    ])\n\
  ))\n\
");
