// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `gleam` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "as",
    "assert",
    "auto",
    "case",
    "const",
    "delegate",
    "derive",
    "echo",
    "else",
    "external",
    "fn",
    "if",
    "implement",
    "import",
    "let",
    "macro",
    "opaque",
    "panic",
    "pub",
    "test",
    "todo",
    "type",
    "use",
];

pub const LOCALS_SCM: Option<&str> = Some("; Scopes\n\
(block) @local.scope\n\
\n\
(function) @local.scope\n\
\n\
(case_clause) @local.scope\n\
\n\
; Definitions\n\
(let pattern: (identifier) @local.definition)\n\
(function_parameter name: (identifier) @local.definition)\n\
(list_pattern (identifier) @local.definition)\n\
(list_pattern assign: (identifier) @local.definition)\n\
(tuple_pattern (identifier) @local.definition)\n\
(record_pattern_argument pattern: (identifier) @local.definition)\n\
\n\
; References\n\
(identifier) @local.reference\n\
");
