// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `hare` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "abort",
    "alloc",
    "append",
    "as",
    "assert",
    "bool",
    "break",
    "char",
    "const",
    "continue",
    "def",
    "defer",
    "delete",
    "else",
    "enum",
    "export",
    "fn",
    "for",
    "free",
    "if",
    "is",
    "len",
    "let",
    "match",
    "nullable",
    "offset",
    "return",
    "size",
    "static",
    "struct",
    "switch",
    "true",
    "type",
    "union",
    "use",
];

pub const LOCALS_SCM: Option<&str> = Some("(unit) @local.scope\n\
\n\
(function_declaration) @local.scope\n\
\n\
(global_binding\n\
  (identifier) @local.definition)\n\
(constant_binding \n\
  (identifier) @local.definition)\n\
(type_bindings\n\
  (identifier) @local.definition)\n\
\n\
(function_declaration\n\
  (prototype\n\
    (parameter_list\n\
      (parameters\n\
        (parameter\n\
          (name) @local.definition)))))\n\
\n\
(identifier) @local.reference\n\
");
