// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `haskell` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "IO",
    "anyclass",
    "as",
    "case",
    "class",
    "data",
    "deriving",
    "do",
    "else",
    "family",
    "forall",
    "hiding",
    "if",
    "import",
    "in",
    "infix",
    "infixl",
    "infixr",
    "instance",
    "let",
    "main",
    "mdo",
    "module",
    "newtype",
    "of",
    "otherwise",
    "pattern",
    "qq",
    "qualified",
    "rec",
    "stock",
    "then",
    "type",
    "via",
    "where",
];

pub const LOCALS_SCM: Option<&str> = Some(
    "(signature name: (variable)) @local.definition\n\
(function name: (variable)) @local.definition\n\
(pattern/variable) @local.definition\n\
(expression/variable) @local.reference\n\
",
);
