// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `javascript` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "arguments",
    "as",
    "async",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "console",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "document",
    "else",
    "export",
    "extends",
    "finally",
    "for",
    "from",
    "function",
    "get",
    "if",
    "import",
    "in",
    "instanceof",
    "let",
    "module",
    "new",
    "of",
    "require",
    "return",
    "set",
    "static",
    "switch",
    "target",
    "throw",
    "try",
    "typeof",
    "var",
    "void",
    "while",
    "window",
    "with",
    "yield",
];

pub const LOCALS_SCM: Option<&str> = Some(
    "; Scopes\n\
;-------\n\
\n\
[\n\
  (statement_block)\n\
  (function_expression)\n\
  (arrow_function)\n\
  (function_declaration)\n\
  (method_definition)\n\
] @local.scope\n\
\n\
; Definitions\n\
;------------\n\
\n\
(pattern/identifier) @local.definition\n\
\n\
(variable_declarator\n\
  name: (identifier) @local.definition)\n\
\n\
; References\n\
;------------\n\
\n\
(identifier) @local.reference\n\
",
);
