// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `kotlin` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "Regex",
    "class",
    "enum",
    "field",
    "fromLiteral",
    "interface",
    "it",
    "object",
    "toRegex",
    "typealias",
    "typeof",
    "val",
    "var",
];

pub const LOCALS_SCM: Option<&str> = None;
