// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `lua` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "and", "do", "end", "function", "global", "goto", "in", "local", "not", "or", "return", "self",
];

pub const LOCALS_SCM: Option<&str> = Some(
    "; Scopes\n\
[\n\
  (chunk)\n\
  (do_statement)\n\
  (while_statement)\n\
  (repeat_statement)\n\
  (if_statement)\n\
  (for_statement)\n\
  (function_declaration)\n\
  (function_definition)\n\
] @local.scope\n\
\n\
; Definitions\n\
(assignment_statement\n\
  (variable_list\n\
    (identifier) @local.definition))\n\
\n\
(function_declaration\n\
  name: (identifier) @local.definition)\n\
\n\
(for_generic_clause\n\
  (variable_list\n\
    (identifier) @local.definition))\n\
\n\
(for_numeric_clause\n\
  name: (identifier) @local.definition)\n\
\n\
(parameters\n\
  (identifier) @local.definition)\n\
\n\
; References\n\
(identifier) @local.reference\n\
",
);
