// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `nix` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "__add",
    "__addErrorContext",
    "__all",
    "__any",
    "__appendContext",
    "__attrNames",
    "__attrValues",
    "__bitAnd",
    "__bitOr",
    "__bitXor",
    "__catAttrs",
    "__ceil",
    "__compareVersions",
    "__concatLists",
    "__concatMap",
    "__concatStringsSep",
    "__currentSystem",
    "__currentTime",
    "__deepSeq",
    "__div",
    "__elem",
    "__elemAt",
    "__fetchurl",
    "__filter",
    "__filterSource",
    "__findFile",
    "__flakeRefToString",
    "__floor",
    "__foldl'",
    "__fromJSON",
    "__functionArgs",
    "__genList",
    "__genericClosure",
    "__getAttr",
    "__getContext",
    "__getEnv",
    "__getFlake",
    "__groupBy",
    "__hasAttr",
    "__hasContext",
    "__hashFile",
    "__hashString",
    "__head",
    "__intersectAttrs",
    "__isAttrs",
    "__isBool",
    "__isFloat",
    "__isFunction",
    "__isInt",
    "__isList",
    "__isPath",
    "__isString",
    "__langVersion",
    "__length",
    "__lessThan",
    "__listToAttrs",
    "__mapAttrs",
    "__match",
    "__mul",
    "__nixPath",
    "__nixVersion",
    "__parseDrvName",
    "__parseFlakeRef",
    "__partition",
    "__path",
    "__pathExists",
    "__readDir",
    "__readFile",
    "__readFileType",
    "__replaceStrings",
    "__seq",
    "__sort",
    "__split",
    "__splitVersion",
    "__storeDir",
    "__storePath",
    "__stringLength",
    "__sub",
    "__substring",
    "__tail",
    "__toFile",
    "__toJSON",
    "__toPath",
    "__toXML",
    "__trace",
    "__traceVerbose",
    "__tryEval",
    "__typeOf",
    "__unsafeDiscardOutputDependency",
    "__unsafeDiscardStringContext",
    "__unsafeGetAttrPos",
    "__zipAttrsWith",
    "abort",
    "assert",
    "baseNameOf",
    "break",
    "builtins",
    "derivation",
    "derivationStrict",
    "dirOf",
    "else",
    "false",
    "fetchGit",
    "fetchMercurial",
    "fetchTarball",
    "fetchTree",
    "fromTOML",
    "if",
    "import",
    "in",
    "inherit",
    "isNull",
    "let",
    "map",
    "null",
    "or",
    "placeholder",
    "rec",
    "removeAttrs",
    "scopedImport",
    "then",
    "throw",
    "toString",
    "true",
    "with",
];

pub const LOCALS_SCM: Option<&str> = Some(";; when using @local.reference, tree-sitter seems to \n\
;; apply the scope from the identifier it has looked up,\n\
;; which makes sense for most languages.\n\
;; however, we want to highlight things as function based on their call-site,\n\
;; not their definition; therefore using TS's support for tracking locals\n\
;; impedes our ability to get the highlighting we want.\n\
;;\n\
;; also, TS doesn't seem to support scoping as implemented in languages\n\
;; with lazy let bindings, which results in syntax highlighting/goto-reference\n\
;; results that depend on the order of definitions, which is counter to the\n\
;; semantics of Nix.\n\
;;\n\
;; so for now we'll opt for not having any locals queries.\n\
;;\n\
;; see: https://github.com/tree-sitter/tree-sitter/issues/918\n\
\n\
;(function_expression\n\
;  universal: (identifier)? @local.definition\n\
;  formals: (formals (formal name: (identifier) @local.definition)*)\n\
;  universal: (identifier)? @local.definition\n\
;  ) @local.scope\n\
;\n\
;(rec_attrset_expression\n\
;  bind: (binding\n\
;    attrpath: (attrpath . (attr_identifier) @local.definition)) \n\
;) @local.scope\n\
;\n\
;(let_expression\n\
;  bind: (binding\n\
;    attrpath: (attrpath . (attr_identifier) @local.definition)) \n\
;) @local.scope\n\
;\n\
;(identifier) @local.reference \n\
");
