// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `ocaml` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "and",
    "array",
    "as",
    "assert",
    "begin",
    "bool",
    "bytes",
    "char",
    "class",
    "constraint",
    "do",
    "done",
    "downto",
    "effect",
    "else",
    "end",
    "exception",
    "exn",
    "external",
    "float",
    "for",
    "format6",
    "fun",
    "function",
    "functor",
    "if",
    "in",
    "include",
    "inherit",
    "initializer",
    "int",
    "int32",
    "int64",
    "lazy",
    "lazy_t",
    "let",
    "list",
    "match",
    "method",
    "module",
    "mutable",
    "nativeint",
    "new",
    "nonrec",
    "object",
    "of",
    "open",
    "option",
    "private",
    "rec",
    "sig",
    "string",
    "struct",
    "then",
    "to",
    "try",
    "type",
    "unit",
    "val",
    "virtual",
    "when",
    "while",
    "with",
];

pub const LOCALS_SCM: Option<&str> = Some("; Scopes\n\
;-------\n\
\n\
[\n\
  (let_binding)\n\
  (class_binding)\n\
  (class_function)\n\
  (method_definition)\n\
  (fun_expression)\n\
  (object_expression)\n\
  (for_expression)\n\
  (match_case)\n\
  (attribute_payload)\n\
] @local.scope\n\
\n\
; Definitions\n\
;------------\n\
\n\
(value_pattern) @local.definition\n\
\n\
; References\n\
;-----------\n\
\n\
(value_path . (value_name) @local.reference)\n\
");
