// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `odin` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "auto_cast",
    "bit_field",
    "bit_set",
    "cast",
    "defer",
    "enum",
    "foreign",
    "in",
    "map",
    "matrix",
    "not_in",
    "or_else",
    "or_return",
    "proc",
    "return",
    "struct",
    "transmute",
    "union",
    "using",
];

pub const LOCALS_SCM: Option<&str> = Some(
    "; Scopes\n\
\n\
[\n\
  (block)\n\
  (declaration)\n\
  (statement)\n\
] @scope\n\
\n\
; References\n\
\n\
(identifier) @reference\n\
\n\
; Definitions\n\
\n\
(package_declaration (identifier) @definition.namespace)\n\
\n\
(import_declaration alias: (identifier) @definition.namespace)\n\
\n\
(procedure_declaration (identifier) @definition.function)\n\
\n\
(struct_declaration (identifier) @definition.type \"::\")\n\
\n\
(enum_declaration (identifier) @definition.enum \"::\")\n\
\n\
(union_declaration (identifier) @definition.type \"::\")\n\
\n\
(bit_field_declaration (identifier) @definition.type \"::\")\n\
\n\
(variable_declaration (identifier) @definition.var \":=\")\n\
\n\
(const_declaration (identifier) @definition.constant \"::\")\n\
\n\
(const_type_declaration (identifier) @definition.type \":\")\n\
\n\
(parameter (identifier) @definition.parameter \":\"?)\n\
\n\
(default_parameter (identifier) @definition.parameter \":=\")\n\
\n\
(field (identifier) @definition.field \":\")\n\
\n\
(label_statement (identifier) @definition \":\")\n\
",
);
