// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `pascal` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[];

pub const LOCALS_SCM: Option<&str> = Some(
    "\n\
(root)                                   @local.scope\n\
\n\
(defProc)                                @local.scope\n\
(lambda)                                 @local.scope\n\
(interface   (declProc)                  @local.scope)\n\
(declSection (declProc)                  @local.scope)\n\
(declClass   (declProc)                  @local.scope)\n\
(declHelper  (declProc)                  @local.scope)\n\
(declProcRef)                            @local.scope\n\
\n\
(exceptionHandler)                       @local.scope\n\
(exceptionHandler variable: (identifier) @local.definition)\n\
\n\
(declArg          name: (identifier)     @local.definition)\n\
(declVar          name: (identifier)     @local.definition)\n\
(declConst        name: (identifier)     @local.definition)\n\
(declLabel        name: (identifier)     @local.definition)\n\
(genericArg       name: (identifier)     @local.definition)\n\
(declEnumValue    name: (identifier)     @local.definition)\n\
(declType         name: (identifier)     @local.definition)\n\
(declType         name: (genericTpl entity: (identifier)     @local.definition))\n\
\n\
(declProc         name: (identifier)     @local.definition)\n\
\n\
(identifier)                             @local.reference\n\
",
);
