// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `powershell` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "begin",
    "break",
    "catch",
    "continue",
    "data",
    "do",
    "dynamicparam",
    "else",
    "elseif",
    "end",
    "exit",
    "filter",
    "finally",
    "for",
    "foreach",
    "function",
    "if",
    "inlinescript",
    "parallel",
    "param",
    "process",
    "return",
    "sequence",
    "switch",
    "throw",
    "trap",
    "try",
    "until",
    "while",
    "workflow",
];

pub const LOCALS_SCM: Option<&str> = None;
