// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `prisma` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "datasource",
    "enum",
    "generator",
    "model",
];

pub const LOCALS_SCM: Option<&str> = None;
