// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `proto` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "edition",
    "enum",
    "import",
    "message",
    "oneof",
    "option",
    "package",
    "repeated",
    "reserved",
    "returns",
    "rpc",
    "service",
    "syntax",
    "to",
];

pub const LOCALS_SCM: Option<&str> = None;
