// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `puppet` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "and", "class", "define", "function", "in", "inherits", "node", "or", "tag", "type",
];

pub const LOCALS_SCM: Option<&str> = Some(
    "; Scopes\n\
\n\
[\n\
  (block)\n\
  (defined_resource_type)\n\
  (parameter_list)\n\
  (attribute_type_entry)\n\
  (class_definition)\n\
  (node_definition)\n\
  (resource_declaration)\n\
  (selector)\n\
  (iterator_statement)\n\
  (case_statement)\n\
  (hash)\n\
  (array)\n\
] @scope\n\
\n\
; References\n\
\n\
[\n\
  (identifier)\n\
  (class_identifier)\n\
  (variable) \n\
] @reference\n\
\n\
; Definitions\n\
\n\
(attribute [(identifier) (variable)] @definition.field)\n\
\n\
(function_declaration\n\
  [(identifier) (class_identifier)] @definition.function)\n\
\n\
(include_statement [(identifier) (class_identifier)] @definition.import)\n\
\n\
(parameter (variable) @definition.parameter)\n\
\n\
(class_definition\n\
  [(identifier) (class_identifier)] @definition.type)\n\
\n\
(node_definition\n\
  (node_name (identifier) @definition.type))\n\
\n\
(resource_declaration\n\
  [(identifier) (class_identifier)] @definition.type)\n\
\n\
(assignment . (variable) @definition.var)\n\
",
);
