// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `r` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &["function", "in"];

pub const LOCALS_SCM: Option<&str> = Some(
    "; locals.scm\n\
\n\
(function_definition) @local.scope\n\
\n\
(argument  name: (identifier) @local.definition)\n\
(parameter name: (identifier) @local.definition)\n\
\n\
(binary_operator\n\
    lhs: (identifier) @local.definition\n\
    operator: \"<-\")\n\
(binary_operator\n\
    lhs: (identifier) @local.definition\n\
    operator: \"=\")\n\
(binary_operator\n\
    operator: \"->\"\n\
    rhs: (identifier) @local.definition)\n\
\n\
(identifier) @local.reference\n\
",
);
