// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `ruby` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "alias",
    "and",
    "begin",
    "break",
    "case",
    "class",
    "def",
    "do",
    "else",
    "elsif",
    "end",
    "ensure",
    "for",
    "if",
    "in",
    "module",
    "next",
    "or",
    "private",
    "protected",
    "public",
    "rescue",
    "retry",
    "return",
    "then",
    "unless",
    "until",
    "when",
    "while",
    "yield",
];

pub const LOCALS_SCM: Option<&str> = Some("((method) @local.scope\n\
 (#set! local.scope-inherits false))\n\
\n\
[\n\
  (lambda)\n\
  (block)\n\
  (do_block)\n\
] @local.scope\n\
\n\
(block_parameter (identifier) @local.definition)\n\
(block_parameters (identifier) @local.definition)\n\
(destructured_parameter (identifier) @local.definition)\n\
(hash_splat_parameter (identifier) @local.definition)\n\
(lambda_parameters (identifier) @local.definition)\n\
(method_parameters (identifier) @local.definition)\n\
(splat_parameter (identifier) @local.definition)\n\
\n\
(keyword_parameter name: (identifier) @local.definition)\n\
(optional_parameter name: (identifier) @local.definition)\n\
\n\
(identifier) @local.reference\n\
\n\
(assignment left: (identifier) @local.definition)\n\
(operator_assignment left: (identifier) @local.definition)\n\
(left_assignment_list (identifier) @local.definition)\n\
(rest_assignment (identifier) @local.definition)\n\
(destructured_left_assignment (identifier) @local.definition)\n\
");
