// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `scala` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "case",
    "class",
    "def",
    "derives",
    "end",
    "enum",
    "extends",
    "extension",
    "finally",
    "given",
    "implicit",
    "new",
    "object",
    "override",
    "package",
    "return",
    "trait",
    "type",
    "using",
    "val",
    "var",
    "with",
];

pub const LOCALS_SCM: Option<&str> = Some("(template_body) @local.scope\n\
(lambda_expression) @local.scope\n\
\n\
\n\
(function_declaration\n\
      name: (identifier) @local.definition) @local.scope\n\
\n\
(function_definition\n\
      name: (identifier) @local.definition)\n\
\n\
(parameter\n\
  name: (identifier) @local.definition)\n\
\n\
(binding\n\
  name: (identifier) @local.definition)\n\
\n\
(val_definition\n\
  pattern: (identifier) @local.definition)\n\
\n\
(var_definition\n\
  pattern: (identifier) @local.definition)\n\
\n\
(val_declaration\n\
  name: (identifier) @local.definition)\n\
\n\
(var_declaration\n\
  name: (identifier) @local.definition)\n\
\n\
(identifier) @local.reference\n\
\n\
");
