// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `swift` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "any",
    "async",
    "await",
    "break",
    "case",
    "class",
    "continue",
    "convenience",
    "deinit",
    "didSet",
    "do",
    "enum",
    "extension",
    "fallthrough",
    "for",
    "func",
    "guard",
    "if",
    "import",
    "in",
    "indirect",
    "let",
    "nil",
    "nonisolated",
    "override",
    "protocol",
    "repeat",
    "required",
    "return",
    "some",
    "struct",
    "subscript",
    "switch",
    "typealias",
    "unowned",
    "var",
    "weak",
    "while",
    "willSet",
];

pub const LOCALS_SCM: Option<&str> = Some(
    "(import_declaration\n\
  (identifier) @local.definition.import)\n\
\n\
(function_declaration\n\
  name: (simple_identifier) @local.definition.function)\n\
\n\
; Scopes\n\
[\n\
  (statements)\n\
  (for_statement)\n\
  (while_statement)\n\
  (repeat_while_statement)\n\
  (do_statement)\n\
  (if_statement)\n\
  (guard_statement)\n\
  (switch_statement)\n\
  (property_declaration)\n\
  (function_declaration)\n\
  (class_declaration)\n\
  (protocol_declaration)\n\
] @local.scope\n\
\n\
\n\
",
);
