// AUTO-GENERATED by build.rs — do not edit manually.
// Builtins and locals.scm content for `typescript` extracted from tree-sitter grammar.

pub const BUILTINS: &[&str] = &[
    "abstract",
    "declare",
    "enum",
    "export",
    "implements",
    "interface",
    "keyof",
    "namespace",
    "override",
    "private",
    "protected",
    "public",
    "readonly",
    "satisfies",
    "type",
];

pub const LOCALS_SCM: Option<&str> = Some(
    "(required_parameter (identifier) @local.definition)\n\
(optional_parameter (identifier) @local.definition)\n\
",
);
