// =============================================================================
// elixir/externals.rs — Elixir macro-injected and framework-global names
//
// Elixir's `use Module` macro injects functions into the calling module at
// compile time. The names are never defined in project source — they are
// code-generated by the target module's `__using__/1` callback. Without
// treating them as externals, the resolution engine produces false unresolved
// refs for names like `render`, `assign`, `cast`, `field`, etc.
//
// Two tiers:
//   EXTERNALS     — always-external, no dep check required. These are names
//                   that Kernel or OTP inject unconditionally and that are not
//                   already covered by `builtins::is_elixir_builtin`.
//   framework_globals — dep-gated. Only active when the corresponding hex
//                   package appears in mix.exs dependencies.
// =============================================================================

/// Always-external Elixir names not covered by `is_elixir_builtin`.
///
/// Most unconditional Kernel macros and ExUnit assertions are already handled
/// by `builtins::is_elixir_builtin` (called directly in the resolver).
/// This list covers operators and special forms that tree-sitter surfaces as
/// identifiers and would otherwise appear as unresolved refs.
pub(crate) const EXTERNALS: &[&str] = &[
    // Kernel operators / special forms emitted as identifiers by the extractor
    "|>",
    "&&",
    "||",
    "!",
    "not",
    "and",
    "or",
    "when",
    "in",
    // Additional Kernel macros not in is_elixir_builtin
    "binding",
    "dbg",
    "sigil_c",
    "sigil_C",
    "sigil_d",
    "sigil_D",
    "sigil_n",
    "sigil_N",
    "sigil_r",
    "sigil_R",
    "sigil_s",
    "sigil_S",
    "sigil_t",
    "sigil_T",
    "sigil_u",
    "sigil_U",
    "sigil_w",
    "sigil_W",
    // Erlang interop
    "to_atom",
    "binary_to_term",
    "term_to_binary",
];

