// =============================================================================
// elixir/externals.rs — Elixir macro-injected and framework-global names
//
// Elixir's `use Module` macro injects functions into the calling module at
// compile time. The names are never defined in project source — they are
// code-generated by the target module's `__using__/1` callback. Without
// treating them as externals, the resolution engine produces false unresolved
// refs for names like `render`, `assign`, `cast`, `field`, etc.
//
// Two tiers:
//   EXTERNALS     — always-external, no dep check required. These are names
//                   that Kernel or OTP inject unconditionally and that are not
//                   already covered by `builtins::is_elixir_builtin`.
//   framework_globals — dep-gated. Only active when the corresponding hex
//                   package appears in mix.exs dependencies.
// =============================================================================

use std::collections::HashSet;

/// Always-external Elixir names not covered by `is_elixir_builtin`.
///
/// Most unconditional Kernel macros and ExUnit assertions are already handled
/// by `builtins::is_elixir_builtin` (called directly in the resolver).
/// This list covers operators and special forms that tree-sitter surfaces as
/// identifiers and would otherwise appear as unresolved refs.
pub(crate) const EXTERNALS: &[&str] = &[
    // Kernel operators / special forms emitted as identifiers by the extractor
    "|>",
    "&&",
    "||",
    "!",
    "not",
    "and",
    "or",
    "when",
    "in",
    // Additional Kernel macros not in is_elixir_builtin
    "binding",
    "dbg",
    "sigil_c",
    "sigil_C",
    "sigil_d",
    "sigil_D",
    "sigil_n",
    "sigil_N",
    "sigil_r",
    "sigil_R",
    "sigil_s",
    "sigil_S",
    "sigil_t",
    "sigil_T",
    "sigil_u",
    "sigil_U",
    "sigil_w",
    "sigil_W",
    // Erlang interop
    "to_atom",
    "binary_to_term",
    "term_to_binary",
];

/// Dependency-gated macro-injected globals for Elixir.
///
/// Each block fires when the matching hex package name appears in mix.exs
/// `deps`. Mix dep atoms are snake_case (e.g. `"phoenix"`, `"ecto_sql"`).
pub(crate) fn framework_globals(deps: &HashSet<String>) -> Vec<&'static str> {
    let mut globals: Vec<&'static str> = Vec::new();

    // -------------------------------------------------------------------------
    // Phoenix — web framework
    // Injected via: use Phoenix.Controller, use Phoenix.LiveView, etc.
    // -------------------------------------------------------------------------
    if deps.contains("phoenix") {
        // Phoenix.Controller — use Phoenix.Controller injects all of these
        globals.extend(PHOENIX_CONTROLLER);
        // Phoenix.Router — use Phoenix.Router / scope/pipeline macros
        globals.extend(PHOENIX_ROUTER);
        // Phoenix.HTML helpers
        globals.extend(PHOENIX_HTML);
        // Phoenix.Component (LiveComponent / function components)
        globals.extend(PHOENIX_COMPONENT);
    }

    // Phoenix.LiveView (often a separate dep: :phoenix_live_view)
    if deps.contains("phoenix") || deps.contains("phoenix_live_view") {
        globals.extend(PHOENIX_LIVEVIEW);
    }

    // Phoenix.ConnTest — injected via `use MyApp.ConnCase`
    if deps.contains("phoenix") || deps.contains("plug") {
        globals.extend(PHOENIX_CONN_TEST);
    }

    // -------------------------------------------------------------------------
    // Ecto — database ORM
    // Injected via: use Ecto.Schema, use Ecto.Migration, import Ecto.Changeset, etc.
    // -------------------------------------------------------------------------
    if deps.contains("ecto") || deps.contains("ecto_sql") {
        globals.extend(ECTO_SCHEMA);
        globals.extend(ECTO_CHANGESET);
        globals.extend(ECTO_QUERY);
        globals.extend(ECTO_MIGRATION);
    }

    // -------------------------------------------------------------------------
    // Plug — HTTP middleware
    // Injected via: use Plug.Builder / import Plug.Conn
    // -------------------------------------------------------------------------
    if deps.contains("plug") || deps.contains("plug_cowboy") {
        globals.extend(PLUG_CONN);
    }

    // -------------------------------------------------------------------------
    // ExUnit — stdlib test framework (always available, but gate on ex_unit
    // explicitly in case of non-test builds; ExUnit itself is always present
    // in the OTP release, so the dep may appear as :ex_unit or not at all in
    // mix.exs when using mix test defaults).
    // -------------------------------------------------------------------------
    // ExUnit macros are already handled unconditionally by is_elixir_builtin.
    // Add the remaining ExUnit helpers not in that list.
    globals.extend(EXUNIT_EXTRA);

    // -------------------------------------------------------------------------
    // Mox — mock library
    // -------------------------------------------------------------------------
    if deps.contains("mox") || deps.contains("mock") {
        globals.extend(MOX_GLOBALS);
    }

    // -------------------------------------------------------------------------
    // ExMachina — factory / fixture library
    // -------------------------------------------------------------------------
    if deps.contains("ex_machina") {
        globals.extend(EX_MACHINA_GLOBALS);
    }

    // -------------------------------------------------------------------------
    // Absinthe — GraphQL
    // -------------------------------------------------------------------------
    if deps.contains("absinthe") || deps.contains("absinthe_plug") {
        globals.extend(ABSINTHE_GLOBALS);
    }

    // -------------------------------------------------------------------------
    // Oban — background jobs
    // -------------------------------------------------------------------------
    if deps.contains("oban") {
        globals.extend(&["perform", "new", "new_with_schedule", "cancel_job", "retry_job"]);
    }

    // -------------------------------------------------------------------------
    // Gettext — i18n
    // -------------------------------------------------------------------------
    if deps.contains("gettext") {
        globals.extend(&[
            "gettext",
            "ngettext",
            "dgettext",
            "dngettext",
            "pgettext",
            "dpgettext",
        ]);
    }

    globals
}

// =============================================================================
// Phoenix — injected function names per module
// =============================================================================

/// Phoenix.Controller — `use Phoenix.Controller` injects these into controller modules.
const PHOENIX_CONTROLLER: &[&str] = &[
    "render",
    "redirect",
    "put_flash",
    "put_status",
    "put_layout",
    "put_view",
    "json",
    "text",
    "html",
    "send_resp",
    "scrub_params",
    "action_name",
    "controller_module",
    "plug",
    "action_fallback",
    "send_download",
    "send_file",
    "fetch_flash",
    "clear_flash",
    "halt",
];

/// Phoenix.LiveView — `use Phoenix.LiveView` injects these.
const PHOENIX_LIVEVIEW: &[&str] = &[
    "assign",
    "assign_new",
    "push_event",
    "push_navigate",
    "push_patch",
    "socket",
    "connected?",
    "live_render",
    "render_slot",
    "handle_event",
    "handle_info",
    "handle_params",
    "mount",
    "on_mount",
    "handle_async",
    "assign_async",
    "start_async",
    "cancel_async",
    "update",
    "stream",
    "stream_insert",
    "stream_delete",
    "stream_configure",
    "attach_hook",
    "detach_hook",
    "put_flash",
    "clear_flash",
    "redirect",
    "navigate",
    "patch",
    "send_update",
    "send_update_after",
    "send_info",
    "allow_upload",
    "consume_uploaded_entries",
    "cancel_upload",
    "uploaded_entries",
];

/// Phoenix.Component — `use Phoenix.Component` / `embed_templates`.
const PHOENIX_COMPONENT: &[&str] = &[
    "attr",
    "slot",
    "embed_templates",
    "sigil_H",
    "assigns_to_attributes",
    "used_input?",
    "normalize_attribute",
];

/// Phoenix.Router — `use Phoenix.Router` macros AND the auto-generated
/// `Routes` module that Phoenix injects into every controller / view / test
/// module via `use MyAppWeb, :controller` / `use MyAppWeb.ConnCase`. The
/// individual `*_path` / `*_url` helper functions on `Routes` are synthesised
/// at compile time from the router's route declarations and never appear as
/// source-defined symbols — the module itself has to be classified external
/// to avoid thousands of unresolved `Routes.foo_path(...)` receiver refs.
const PHOENIX_ROUTER: &[&str] = &[
    "get",
    "post",
    "put",
    "patch",
    "delete",
    "options",
    "head",
    "resources",
    "scope",
    "pipe_through",
    "forward",
    "live",
    "pipeline",
    "plug",
    "live_session",
    "live_dashboard",
    // Auto-generated route helper module injected into controllers, views,
    // and ConnCase-aliased test modules. Present in every Phoenix project.
    "Routes",
    // Phoenix 1.7+ verified routes sigil + `url` / `path` builders.
    "sigil_p",
    "url",
    "path",
    "static_path",
    "static_url",
    "static_integrity",
];

/// Phoenix.HTML — `use Phoenix.HTML` / `import Phoenix.HTML`.
const PHOENIX_HTML: &[&str] = &[
    "form_for",
    "text_input",
    "select",
    "submit",
    "link",
    "content_tag",
    "raw",
    "sigil_E",
    "sigil_e",
    "tag",
    "label",
    "checkbox",
    "radio_button",
    "textarea",
    "number_input",
    "email_input",
    "password_input",
    "hidden_input",
    "file_input",
    "telephone_input",
    "url_input",
    "search_input",
    "color_input",
    "range_input",
    "date_input",
    "time_input",
    "datetime_local_input",
    "html_escape",
    "safe_to_string",
];

/// Phoenix.ConnTest — `use Phoenix.ConnTest` in test support modules.
const PHOENIX_CONN_TEST: &[&str] = &[
    "html_response",
    "json_response",
    "text_response",
    "redirected_to",
    "recycle",
    "build_conn",
    "assert_error_sent",
    "dispatch",
    "bypass_through",
];

// =============================================================================
// Ecto — injected via schema/migration/changeset macros
// =============================================================================

/// Ecto.Schema — `use Ecto.Schema` injects schema/field/association macros.
const ECTO_SCHEMA: &[&str] = &[
    "schema",
    "embedded_schema",
    "field",
    "belongs_to",
    "has_many",
    "has_one",
    "many_to_many",
    "embeds_one",
    "embeds_many",
    "timestamps",
    "primary_key",
    "foreign_key",
];

/// Ecto.Changeset — `import Ecto.Changeset` brings these into scope.
const ECTO_CHANGESET: &[&str] = &[
    "cast",
    "cast_assoc",
    "cast_embed",
    "validate_required",
    "validate_format",
    "validate_length",
    "validate_inclusion",
    "validate_exclusion",
    "validate_change",
    "validate_number",
    "validate_acceptance",
    "validate_confirmation",
    "validate_subset",
    "unique_constraint",
    "foreign_key_constraint",
    "assoc_constraint",
    "no_assoc_constraint",
    "exclusion_constraint",
    "check_constraint",
    "put_change",
    "put_assoc",
    "put_embed",
    "force_change",
    "delete_change",
    "apply_action",
    "apply_action!",
    "change",
    "add_error",
    "get_field",
    "fetch_field",
    "get_change",
    "fetch_change",
    "traverse_errors",
    "unsafe_validate_unique",
    "optimistic_lock",
    "prepare_changes",
];

/// Ecto.Query — `import Ecto.Query` macro DSL.
const ECTO_QUERY: &[&str] = &[
    "from",
    "where",
    "select",
    "join",
    "preload",
    "order_by",
    "group_by",
    "having",
    "limit",
    "offset",
    "distinct",
    "subquery",
    "dynamic",
    "lock",
    "update",
    "exclude",
    "select_merge",
    "windows",
    "fragment",
];

/// Ecto.Migration — `use Ecto.Migration` DSL.
const ECTO_MIGRATION: &[&str] = &[
    "add",
    "remove",
    "modify",
    "rename",
    "create",
    "create_if_not_exists",
    "alter",
    "drop",
    "drop_if_exists",
    "table",
    "index",
    "unique_index",
    "execute",
    "flush",
    "references",
    "constraint",
    "change",
    "up",
    "down",
    "timestamps",
];

// =============================================================================
// Plug.Conn — import Plug.Conn
// =============================================================================

const PLUG_CONN: &[&str] = &[
    "send_resp",
    "put_resp_header",
    "put_resp_content_type",
    "resp",
    "halt",
    "assign",
    "fetch_query_params",
    "fetch_session",
    "get_session",
    "put_session",
    "delete_session",
    "configure_session",
    "get_req_header",
    "put_req_header",
    "delete_req_header",
    "get_resp_header",
    "delete_resp_header",
    "read_body",
    "send_chunked",
    "chunk",
    "send_file",
    "merge_assigns",
    "merge_private",
    "get_peer_data",
    "get_http_protocol",
];

// =============================================================================
// ExUnit extras — names not in is_elixir_builtin
// =============================================================================

const EXUNIT_EXTRA: &[&str] = &[
    "catch_error",
    "catch_exit",
    "catch_throw",
    "assert_in_delta",
    "assert_lists_equal",
    "assert_maps_equal",
    "doctest",
    "import_fixtures",
    "start_supervised",
    "start_supervised!",
    "stop_supervised",
    "stop_supervised!",
    "with_log",
];

// =============================================================================
// Mox — mock library
// =============================================================================

const MOX_GLOBALS: &[&str] = &[
    "expect",
    "stub",
    "stub_with",
    "verify!",
    "verify_on_exit!",
    "set_mox_global",
    "set_mox_private",
    "allow",
    "reject",
    "defmock",
];

// =============================================================================
// ExMachina — factory / fixture library
// =============================================================================

const EX_MACHINA_GLOBALS: &[&str] = &[
    "build",
    "insert",
    "insert!",
    "params_for",
    "string_params_for",
    "params_with_assocs",
    "string_params_with_assocs",
    "build_pair",
    "insert_pair",
    "build_list",
    "insert_list",
    "sequence",
];

// =============================================================================
// Absinthe — GraphQL schema DSL
// =============================================================================

const ABSINTHE_GLOBALS: &[&str] = &[
    "object",
    "field",
    "arg",
    "resolve",
    "query",
    "mutation",
    "subscription",
    "interface",
    "union",
    "scalar",
    "enum",
    "value",
    "input_object",
    "directive",
    "on",
    "middleware",
    "complexity",
    "non_null",
    "list_of",
    "import_fields",
    "import_types",
];
