// AUTO-GENERATED by build.rs — do not edit manually.
// Dispatcher over per-language data in `query_builtins/<lang>.rs`.
//
// Language IDs are derived from crate names: tree-sitter-foo-1.2.3 → "foo".
// Aliases (tsx→typescript, etc.) are handled by the language plugin registry,
// NOT here — build.rs only knows about crate names.

mod ada;
mod bash;
mod bicep;
mod c;
mod cmake;
mod cpp;
mod csharp;
mod dart;
mod dockerfile;
mod elixir;
mod erlang;
mod fortran;
mod fsharp;
mod gleam;
mod go;
mod hare;
mod haskell;
mod java;
mod javascript;
mod kotlin;
mod lua;
mod make;
mod nix;
mod ocaml;
mod odin;
mod pascal;
mod php;
mod powershell;
mod prisma;
mod proto;
mod puppet;
mod python;
mod r;
mod ruby;
mod rust;
mod scala;
mod starlark;
mod swift;
mod typescript;
mod zig;

/// Return query-extracted builtins for a language.
/// Returns an empty slice for languages without query files.
pub fn query_builtins_for_language(lang: &str) -> &'static [&'static str] {
    match lang {
        "ada" => ada::BUILTINS,
        "bash" => bash::BUILTINS,
        "bicep" => bicep::BUILTINS,
        "c" => c::BUILTINS,
        "cmake" => cmake::BUILTINS,
        "cpp" => cpp::BUILTINS,
        "csharp" => csharp::BUILTINS,
        "dart" => dart::BUILTINS,
        "dockerfile" => dockerfile::BUILTINS,
        "elixir" => elixir::BUILTINS,
        "erlang" => erlang::BUILTINS,
        "fortran" => fortran::BUILTINS,
        "fsharp" => fsharp::BUILTINS,
        "gleam" => gleam::BUILTINS,
        "go" => go::BUILTINS,
        "hare" => hare::BUILTINS,
        "haskell" => haskell::BUILTINS,
        "java" => java::BUILTINS,
        "javascript" => javascript::BUILTINS,
        "kotlin" => kotlin::BUILTINS,
        "lua" => lua::BUILTINS,
        "make" => make::BUILTINS,
        "nix" => nix::BUILTINS,
        "ocaml" => ocaml::BUILTINS,
        "odin" => odin::BUILTINS,
        "php" => php::BUILTINS,
        "powershell" => powershell::BUILTINS,
        "prisma" => prisma::BUILTINS,
        "proto" => proto::BUILTINS,
        "puppet" => puppet::BUILTINS,
        "python" => python::BUILTINS,
        "r" => r::BUILTINS,
        "ruby" => ruby::BUILTINS,
        "rust" => rust::BUILTINS,
        "scala" => scala::BUILTINS,
        "starlark" => starlark::BUILTINS,
        "swift" => swift::BUILTINS,
        "typescript" => typescript::BUILTINS,
        "zig" => zig::BUILTINS,
        _ => &[],
    }
}

/// Return the locals.scm query string for a language, if available.
/// Used by LocalResolver for scope-based local variable resolution.
pub fn locals_scm_for_language(lang: &str) -> Option<&'static str> {
    match lang {
        "ada" => ada::LOCALS_SCM,
        "bicep" => bicep::LOCALS_SCM,
        "dart" => dart::LOCALS_SCM,
        "fsharp" => fsharp::LOCALS_SCM,
        "gleam" => gleam::LOCALS_SCM,
        "hare" => hare::LOCALS_SCM,
        "haskell" => haskell::LOCALS_SCM,
        "javascript" => javascript::LOCALS_SCM,
        "lua" => lua::LOCALS_SCM,
        "nix" => nix::LOCALS_SCM,
        "ocaml" => ocaml::LOCALS_SCM,
        "odin" => odin::LOCALS_SCM,
        "pascal" => pascal::LOCALS_SCM,
        "puppet" => puppet::LOCALS_SCM,
        "r" => r::LOCALS_SCM,
        "ruby" => ruby::LOCALS_SCM,
        "scala" => scala::LOCALS_SCM,
        "starlark" => starlark::LOCALS_SCM,
        "swift" => swift::LOCALS_SCM,
        "typescript" => typescript::LOCALS_SCM,
        _ => None,
    }
}
